# Numpy and Pandas

# 1. What is numpy?

 **NumPy** (Numerical Python) is a popular Python library used for numerical computations. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in data science, machine learning, and scientific computing because it speeds up calculations and makes handling large datasets easier.

# NumPy Basics
Installing & Updating the Package
NumPy comes pre-isntalled if you're using Anaconda. <b> !pip install numpy</b>

In [8]:
import numpy as np

# example: To find the square of 1-5 using numpy
<b>1. using numpy</b>

In [13]:

number = np.array([1,2,3,4,5])
print(number)
print(number**2)

[1 2 3 4 5]
[ 1  4  9 16 25]

<b> 2. Using list </b>

In [18]:
numbers = {1,2,3,4,5}
for num in numbers:
    print(num ** 2)

1
4
9
16
25

# 2. What is pandas?
**Pandas** is a powerful Python library used for data manipulation and analysis. It provides easy-to-use data structures like **DataFrame** and **Series** that help organize, clean, and analyze structured data (like tables or spreadsheets). Pandas is essential for tasks such as filtering data, handling missing values, merging datasets, and performing statistical operations, making it a favorite tool for data scientists and analysts.

# Pandas Basic

Installing & Updating the Package Pandas comes pre-isntalled if you're using Anaconda. <b> !pip install pandas</b>

In [29]:
import pandas as pd

data = {
    'Name': ['Shyam', 'Ramesh', 'Sita'],
    'Age': [24, 30, 22],
    'City': ['Kathmandu', 'Pokhara', 'Biratnagar']
}

df = pd.DataFrame(data)
print(df)

     Name  Age        City
0   Shyam   24   Kathmandu
1  Ramesh   30     Pokhara
2    Sita   22  Biratnagar

<b> View first few rows:</b>

In [38]:
df.head()

     Name  Age        City
0   Shyam   24   Kathmandu
1  Ramesh   30     Pokhara
2    Sita   22  Biratnagar

<b>Select a column:</b>

In [53]:
print(df['Age'])

0    24
1    30
2    22
Name: Age, dtype: int64

<b> Filter rows: </b>

In [63]:
print(df[df['Age'] > 23])

     Name  Age       City
0   Shyam   24  Kathmandu
1  Ramesh   30    Pokhara

<b> add new column </b>

In [65]:
df['Age Next Year'] = df['Age'] + 1
print(df)

     Name  Age        City  Age Next Year
0   Shyam   24   Kathmandu             25
1  Ramesh   30     Pokhara             31
2    Sita   22  Biratnagar             23

# Practice

1. Create a NumPy array of your favorite numbers and multiply by 5.

In [74]:
numbers = np.array([1,7,6,8,9,5])
print(numbers*5)

[ 5 35 30 40 45 25]

2. Create a Pandas DataFrame about 3 of your friends with columns like name, age, and city.

In [113]:
friends = {
    'name':['illa','christina','sayal'],
    'age':[28,29,27],
    'city':['Kathmandu','Pyuthan','Jhapa']}
df =pd.DataFrame(friends)

In [115]:
df.head()

        name  age       city
0       illa   28  Kathmandu
1  christina   29    Pyuthan
2      sayal   27      Jhapa

3. Filter your DataFrame to show only friends older than 25.

In [117]:
df['age']

0    28
1    29
2    27
Name: age, dtype: int64

In [123]:
print(df[df['age'] > 25])

        name  age       city
0       illa   28  Kathmandu
1  christina   29    Pyuthan
2      sayal   27      Jhapa

4.Add a new column for “Country” with the value “Nepal” for all.

In [129]:
df['Country']='Nepal'
df

        name  age       city Country
0       illa   28  Kathmandu   Nepal
1  christina   29    Pyuthan   Nepal
2      sayal   27      Jhapa   Nepal