In [3]:
import pandas as pd
import numpy as np

In [5]:
data = {
    'name': ['Rob', 'Rafiq', 'Nina','Sofia','Mohan','Tao','Elon Musk'],
    'income': [5000,6000,4000,7500,8000,7000,10000000]
    
}
df = pd.DataFrame(data)
print(df)

        name    income
0        Rob      5000
1      Rafiq      6000
2       Nina      4000
3      Sofia      7500
4      Mohan      8000
5        Tao      7000
6  Elon Musk  10000000

In [7]:
df.describe()

             income
count  7.000000e+00
mean   1.433929e+06
std    3.777283e+06
min    4.000000e+03
25%    5.500000e+03
50%    7.000000e+03
75%    7.750000e+03
max    1.000000e+07

In [9]:
df.income.quantile(0.75)

7750.0

In [11]:
df.income.quantile(0.75, interpolation ='higher')

8000

# Remove outlier which is elon musk

In [14]:
percentile_99 = df.income.quantile(0.99)
percentile_99

9400479.999999994

In [18]:
df_no_outlier = df[df.income <=percentile_99]
df_no_outlier

    name  income
0    Rob    5000
1  Rafiq    6000
2   Nina    4000
3  Sofia    7500
4  Mohan    8000
5    Tao    7000

# filling missing values

In [23]:
# first remove values
df

        name    income
0        Rob      5000
1      Rafiq      6000
2       Nina      4000
3      Sofia      7500
4      Mohan      8000
5        Tao      7000
6  Elon Musk  10000000

In [29]:
df['income'][3]=np.NaN

/var/folders/hf/wwv96j7x4k72h7npdvq8xbx80000gn/T/ipykernel_1518/3054271026.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['income'][3]=np.NaN
/var/folders/hf/wwv96j7x4k72h7npdvq8xbx80000gn/T/ipykernel_1518/3054271026.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['income'][3]=np.NaN

In [31]:
df

        name      income
0        Rob      5000.0
1      Rafiq      6000.0
2       Nina      4000.0
3      Sofia         NaN
4      Mohan      8000.0
5        Tao      7000.0
6  Elon Musk  10000000.0

In [35]:
df.income.median()

6500.0

In [41]:
df_new =df.fillna(df.income.median())
df_new

        name      income
0        Rob      5000.0
1      Rafiq      6000.0
2       Nina      4000.0
3      Sofia      6500.0
4      Mohan      8000.0
5        Tao      7000.0
6  Elon Musk  10000000.0