In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("transaction.csv")
data

,Transaction Status,Id,Payment Type,Rec Date,Beneficiary Name,Amount,Channel Id,Particulars,Debit Status,Debit Reason Description,Credit Reason Description
0,Success,419883183,Fund Transfer,"10/06/2025, 15:57:45",Chhatradevi Trading and suppliers pvt.lt d.,"5,24,000.00",Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
1,Success,419723027,nQR,"10/06/2025, 12:00:45",PRIME MOTORS PVT.LTD,"16,150.00",Mobile App,PRIME MOTORS PVT.LTD,Success,SUCCESS,SUCCESS
2,Success,419693945,Fund Transfer,"10/06/2025, 11:18:48",bhim bahadur khatri,"45,000.00",Web Channel,salary,Success,SUCCESS,SUCCESS
3,Success,419341381,Fund Transfer,"09/06/2025, 16:24:25",Chhatradevi Trading and suppliers pvt.lt d.,"6,50,000.00",Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
4,Success,419222080,Fund Transfer,"09/06/2025, 13:22:56",Suraj kumar thapa,"13,00,000.00",Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
...,...,...,...,...,...,...,...,...,...,...,...
268,Success,374060791,Fund Transfer,"12/03/2025, 14:07:55",BHUSAL OIL CENTER,"1,00,000.00",Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
269,Success,374051300,Fund Transfer,"12/03/2025, 13:51:45",Bhusal Disels,"1,10,500.00",Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
270,Success,373950257,Fund Transfer,"12/03/2025, 11:14:40",Bhusal Disels,"5,00,000.00",Web Channel,amar njrmam sewa,Success,SUCCESS,SUCCESS
271,Success,373892966,Fund Transfer,"12/03/2025, 09:05:17",Swastika Bhusal,"2,50,000.00",Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
272,Success,373892461,Fund Transfer,"12/03/2025, 09:03:17",BHUSAL OIL CENTER,"1,00,000.00",Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS

In [3]:
data.Amount.describe()

count           273
unique          129
top       50,000.00
freq             30
Name: Amount, dtype: object

In [4]:
data.Amount.describe()

count           273
unique          129
top       50,000.00
freq             30
Name: Amount, dtype: object

In [5]:
data['Amount'] = data['Amount'].str.replace(',', '').astype(float)

In [6]:
highest_transaction = data['Amount'].max()
print("Highest transaction:", highest_transaction)

Highest transaction: 2000000.0

In [7]:
highest_row = data.loc[data['Amount'] == highest_transaction]
print(highest_row)

    Transaction Status         Id   Payment Type              Rec Date  \
125            Success  394641531  Fund Transfer  25/04/2025, 10:54:48

    Beneficiary Name     Amount   Channel Id       Particulars Debit Status  \
125  Swastika Bhusal  2000000.0  Web Channel  amar nirman sewa      Success

    Debit Reason Description Credit Reason Description
125                  SUCCESS                   SUCCESS

# how many times

In [9]:
highest_row = data.loc[data['Amount'] == data['Amount'].max()]
beneficiary_account = highest_row['Beneficiary Name'].values[0]  # Adjust column name

In [10]:
print("Before renaming:", data.columns)
data.rename(columns={'Rec Date': 'Date'}, inplace=True)
print("After renaming:", data.columns)

Before renaming: Index(['Transaction Status', 'Id', 'Payment Type', 'Rec Date',
       'Beneficiary Name', 'Amount', 'Channel Id', 'Particulars',
       'Debit Status', 'Debit Reason Description',
       'Credit Reason Description'],
      dtype='object')
After renaming: Index(['Transaction Status', 'Id', 'Payment Type', 'Date', 'Beneficiary Name',
       'Amount', 'Channel Id', 'Particulars', 'Debit Status',
       'Debit Reason Description', 'Credit Reason Description'],
      dtype='object')

In [11]:
data

,Transaction Status,Id,Payment Type,Date,Beneficiary Name,Amount,Channel Id,Particulars,Debit Status,Debit Reason Description,Credit Reason Description
0,Success,419883183,Fund Transfer,"10/06/2025, 15:57:45",Chhatradevi Trading and suppliers pvt.lt d.,524000.0,Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
1,Success,419723027,nQR,"10/06/2025, 12:00:45",PRIME MOTORS PVT.LTD,16150.0,Mobile App,PRIME MOTORS PVT.LTD,Success,SUCCESS,SUCCESS
2,Success,419693945,Fund Transfer,"10/06/2025, 11:18:48",bhim bahadur khatri,45000.0,Web Channel,salary,Success,SUCCESS,SUCCESS
3,Success,419341381,Fund Transfer,"09/06/2025, 16:24:25",Chhatradevi Trading and suppliers pvt.lt d.,650000.0,Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
4,Success,419222080,Fund Transfer,"09/06/2025, 13:22:56",Suraj kumar thapa,1300000.0,Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
...,...,...,...,...,...,...,...,...,...,...,...
268,Success,374060791,Fund Transfer,"12/03/2025, 14:07:55",BHUSAL OIL CENTER,100000.0,Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
269,Success,374051300,Fund Transfer,"12/03/2025, 13:51:45",Bhusal Disels,110500.0,Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
270,Success,373950257,Fund Transfer,"12/03/2025, 11:14:40",Bhusal Disels,500000.0,Web Channel,amar njrmam sewa,Success,SUCCESS,SUCCESS
271,Success,373892966,Fund Transfer,"12/03/2025, 09:05:17",Swastika Bhusal,250000.0,Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS
272,Success,373892461,Fund Transfer,"12/03/2025, 09:03:17",BHUSAL OIL CENTER,100000.0,Web Channel,amar nirman sewa,Success,SUCCESS,SUCCESS

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273 entries, 0 to 272
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Transaction Status         273 non-null    object
 1   Id                         273 non-null    int64
 2   Payment Type               273 non-null    object
 3   Date                       273 non-null    object
 4   Beneficiary Name           273 non-null    object
 5   Amount                     273 non-null    float64
 6   Channel Id                 273 non-null    object
 7   Particulars                273 non-null    object
 8   Debit Status               273 non-null    object
 9   Debit Reason Description   273 non-null    object
 10  Credit Reason Description  273 non-null    object
dtypes: float64(1), int64(1), object(9)
memory usage: 23.6+ KB

In [13]:
data.drop(columns=['Debit Status','Debit Reason Description','Credit Reason Description'], inplace=True)

In [14]:
data

,Transaction Status,Id,Payment Type,Date,Beneficiary Name,Amount,Channel Id,Particulars
0,Success,419883183,Fund Transfer,"10/06/2025, 15:57:45",Chhatradevi Trading and suppliers pvt.lt d.,524000.0,Web Channel,amar nirman sewa
1,Success,419723027,nQR,"10/06/2025, 12:00:45",PRIME MOTORS PVT.LTD,16150.0,Mobile App,PRIME MOTORS PVT.LTD
2,Success,419693945,Fund Transfer,"10/06/2025, 11:18:48",bhim bahadur khatri,45000.0,Web Channel,salary
3,Success,419341381,Fund Transfer,"09/06/2025, 16:24:25",Chhatradevi Trading and suppliers pvt.lt d.,650000.0,Web Channel,amar nirman sewa
4,Success,419222080,Fund Transfer,"09/06/2025, 13:22:56",Suraj kumar thapa,1300000.0,Web Channel,amar nirman sewa
...,...,...,...,...,...,...,...,...
268,Success,374060791,Fund Transfer,"12/03/2025, 14:07:55",BHUSAL OIL CENTER,100000.0,Web Channel,amar nirman sewa
269,Success,374051300,Fund Transfer,"12/03/2025, 13:51:45",Bhusal Disels,110500.0,Web Channel,amar nirman sewa
270,Success,373950257,Fund Transfer,"12/03/2025, 11:14:40",Bhusal Disels,500000.0,Web Channel,amar njrmam sewa
271,Success,373892966,Fund Transfer,"12/03/2025, 09:05:17",Swastika Bhusal,250000.0,Web Channel,amar nirman sewa
272,Success,373892461,Fund Transfer,"12/03/2025, 09:03:17",BHUSAL OIL CENTER,100000.0,Web Channel,amar nirman sewa

In [15]:
transcation_counts = data['Transaction Status'].value_counts()
print(transcation_counts)

Transaction Status
Success    259
Failed      14
Name: count, dtype: int64

In [16]:
success_count = data[data['Transaction Status'] == 'Success'].shape[0]
failed_count = data[data['Transaction Status'] == 'Failed'].shape[0]

print("Successful transactions:", success_count)
print("Failed transactions:", failed_count)

Successful transactions: 259
Failed transactions: 14

# To found how many time person get transaction

In [18]:
transaction_counts = data.groupby(['Beneficiary Name', 'Transaction Status']).size().reset_index(name='Count')
print(transaction_counts)

                          Beneficiary Name Transaction Status  Count
0                          AKHTAR ALI KHAN            Success      2
1                             ANJU  GURUNG            Success      1
2                  Acharya Hotel And Lodge             Failed      1
3                  Acharya Hotel And Lodge            Success      1
4                         Amar Nirman Sewa             Failed      1
..                                     ...                ...    ...
151                    bhim bahadur khatri            Success      2
152                 binod radiator service            Success      1
153  dreams international holidays pvt ltd            Success      1
154  geo testing and construction pvt.ltd.            Success      1
155                  krishna prasad poudel            Success      1

[156 rows x 3 columns]

In [19]:
total_transactions = data.groupby('Beneficiary Name').size().reset_index(name='TotalCount')
print(total_transactions)

                          Beneficiary Name  TotalCount
0                          AKHTAR ALI KHAN           2
1                             ANJU  GURUNG           1
2                  Acharya Hotel And Lodge           2
3                         Amar Nirman Sewa           1
4                         Amar nirman sewa           1
..                                     ...         ...
140                    bhim bahadur khatri           2
141                 binod radiator service           1
142  dreams international holidays pvt ltd           1
143  geo testing and construction pvt.ltd.           1
144                  krishna prasad poudel           1

[145 rows x 2 columns]

In [20]:

# Merge totals with breakdown
combined = transaction_counts.merge(total_transactions, on='Beneficiary Name')
print(combined)

                          Beneficiary Name Transaction Status  Count  \
0                          AKHTAR ALI KHAN            Success      2
1                             ANJU  GURUNG            Success      1
2                  Acharya Hotel And Lodge             Failed      1
3                  Acharya Hotel And Lodge            Success      1
4                         Amar Nirman Sewa             Failed      1
..                                     ...                ...    ...
151                    bhim bahadur khatri            Success      2
152                 binod radiator service            Success      1
153  dreams international holidays pvt ltd            Success      1
154  geo testing and construction pvt.ltd.            Success      1
155                  krishna prasad poudel            Success      1

     TotalCount
0             2
1             1
2             2
3             2
4             1
..          ...
151           2
152           1
153           1
154           1
155           1

[156 rows x 4 columns]

In [21]:
# Filter for success transactions first (adjust column name and value if needed)
success_data = data[data['Transaction Status'] == 'Success']

# Then group by Beneficiary Name
summary = success_data.groupby('Beneficiary Name').agg(
    Count=('Amount', 'size'),
    TotalAmount=('Amount', 'sum')
).reset_index()

print(summary)

                          Beneficiary Name  Count  TotalAmount
0                          AKHTAR ALI KHAN      2      66000.0
1                             ANJU  GURUNG      1      20000.0
2                  Acharya Hotel And Lodge      1      50000.0
3                         Amar nirman sewa      1     300000.0
4        Anjana nirman sewa company p.lyd.      1     900000.0
..                                     ...    ...          ...
139                    bhim bahadur khatri      2      90000.0
140                 binod radiator service      1       7000.0
141  dreams international holidays pvt ltd      1     500000.0
142  geo testing and construction pvt.ltd.      1     101700.0
143                  krishna prasad poudel      1     300000.0

[144 rows x 3 columns]

In [22]:
# Example beneficiary name
name_to_filter = "Swastika Bhusal"

# Filter data for that beneficiary and successful transactions
filtered_data = data[
    (data['Beneficiary Name'] == name_to_filter) & 
    (data['Transaction Status'] == 'Success')
]

# Aggregate count and sum
summary = filtered_data.agg(
    Count=('Amount', 'size'),
    TotalAmount=('Amount', 'sum')
)

print(f"Summary for {name_to_filter} (Success transactions):")
print(summary)

Summary for Swastika Bhusal (Success transactions):
                Amount
Count             11.0
TotalAmount  3733041.0

In [23]:
# Filter for Swastika Bhusal
prime_data = data[data['Beneficiary Name'] == 'PRIME MOTORS PVT.LTD']

# Group by Amount and count transactions
summary = prime_data.groupby('Amount').size().reset_index(name='Count')

print(summary)

    Amount  Count
0  16150.0      1
1  20000.0      1

In [50]:
# Filter for Swastika Bhusal
swas_data = data[data['Beneficiary Name'] == 'Swastika Bhusal']

# Group by Amount and count transactions
summary1 = swas_data.groupby('Amount').size().reset_index(name='Count')

print(summary1)

       Amount  Count
0      5000.0      1
1     10500.0      1
2     12365.0      1
3     30000.0      1
4     97000.0      2
5    100000.0      1
6    103176.0      1
7    125000.0      1
8    250000.0      1
9   1000000.0      1
10  2000000.0      1